CHANGELOG.md, Cargo.lock, cloud-scanner-cli/Cargo.toml, cloud-scanner-cli/src/aws_api.rs, cloud-scanner-cli/src/lib.rs, cloud-scanner-cli/src/main.rs, cloud-scanner-cli/src/metrics.rs, cloud-scanner-lambda/src/main.rs, cloud-scanner-lambda/src/metrics.rs
Use `anyhow` instead of `unwrap()` to let errors bubble up. See issue #17
=> Feat: improve error handling

CHANGELOG.md, Cargo.lock, cloud-scanner-cli/Cargo.toml, cloud-scanner-cli/src/main.rs
- Upgrade to Clap v 4.0.x to provide CLI parsing and help.
- Other minor dependencies update.
=> Upgrade to Clap v4.0.x

docker-compose.yml
- Use fully qualified image names. Closes #165 .
- Reduce logs verbosity to -vv.
=> fix: podman-compose does not find images of docker-compose file.

CHANGELOG.md, Cargo.lock, cloud-scanner-cli/Cargo.toml, cloud-scanner-cli/src/aws_inventory.rs, cloud-scanner-cli/src/boavizta_api_v1.rs, cloud-scanner-cli/src/cloud_resource.rs, docs/src/SUMMARY.md, docs/src/reference/testing.md
Use latest Boavizta API sdk v0.2.2 and migrate to new API URL's.
Closes #243
=> Use latest Boavizta API sdk v0.2.2

cloud-scanner-cli/src/standalone_server.rs
Create feature to add optional duration on query /metrics (+ fix example in comment on query /impacts) : https://github.com/Boavizta/cloud-scanner/issues/332
=> feat(server): add optional duration parameter when querying for metrics

CHANGELOG.md, cloud-scanner-cli/src/aws_inventory.rs, cloud-scanner-cli/src/boavizta_api_v1.rs, cloud-scanner-cli/src/cloud_resource.rs
=> feat: return instance state with the inventory.

CHANGELOG.md, Cargo.lock, cloud-scanner-cli/Cargo.toml, cloud-scanner-lambda/Cargo.toml, docker-compose.yml
Draft PR
This is mostly working (tested with the dev api).
But we need to await publication of API 1.2.0 docker image to
=> feat: support Boavizta API 1.2.0

CHANGELOG.md, cloud-scanner-cli/src/main.rs
=> fix: use stable public Boavizta API URL by default.

CHANGELOG.md, docker-compose.yml
See https://github.com/Boavizta/cloud-scanner/issues/434
=> feat: add a prometheus data volume in the docker-compose example.

dashboard-config/provisioning/dashboards/grafana-dashboard-cloud-impacts.template.json
This PR does not change the visualisations but simply groups them into rows based per resource type in order to increase readability,
=> Organises the dashboard into rows: Intro / PE / GWP / ADP

cloud-scanner-cli/src/lib.rs, cloud-scanner-cli/src/main.rs
to return the summary of impacts as JSON. See #456
Tested by running `cargo run -- -a us-east-1 estimate --use-duration-hours 1 -s`
=> Add -summary option to estimate command 

Dockerfile
For the moment, theses 2 issues are in "Unapproved" Status and latest alpine docker image not fix these security issues. 
As workournd, I propose to update manually to latest librairy versions of libcrypto3 & libssl3
=> 474-High Security issues status "Unapproved" in latest alpine docker image

dashboard-config/provisioning/dashboards/grafana-dashboard-cloud-impacts.template.json
Fixes 2 vizs that were in the wrong rows, minor changes to titles 
Changed the display so that the projections for  year are just bars and don't show the graph reflecting the variations of the last N hours
=> New version of dashboard

dashboard-config/provisioning/dashboards/default.yml, dashboard-config/provisioning/dashboards/grafana-dashboard-cloud-impacts.template-for-manual-import.json, dashboard-config/provisioning/datasources/prometheus-datasource.yml
Closes #494
Hardcode the UID of  cloud scanner prometheus datasource in the datasource definition and sample dashboard used to provision grafana. Keep a separate version to the dashboard template to permit manual import into Grafana instances that may use a different datasource.
=> fix: automatic provisioning of demo dashboard

CHANGELOG.md, cloud-scanner-cli/src/boavizta_api_v1.rs, cloud-scanner-cli/src/lib.rs, cloud-scanner-cli/src/metric_exporter.rs, cloud-scanner-cli/src/model.rs, cloud-scanner-cli/src/usage_location.rs, docs/src/reference/openapi.json
Closes #265 by adding metadata to the inventory output in json format.
``` json
{
"metadata": {
"estimation_date": "2024-12-14T22:47:25.783194010Z",
"description": "Estimation using Boavizta API",
"cloud_scanner_version": "3.2.0",
"boavizta_api_version": "1.3.6",
"execution_statistics": {
"inventory_duration": {
"secs": 0,
"nanos": 296360816
},
"impact_estimation_duration": {
"secs": 0,
"nanos": 1937
},
"total_duration": {
"secs": 0,
"nanos": 296362753
}
}
},
"impacting_resources": []
}
```
=> feat: return API and scanner versions in the json inventory

CHANGELOG.md, cloud-scanner-cli/src/boavizta_api_v1.rs, cloud-scanner-cli/test-data/DEFAULT_RAW_IMPACTS_OF_M6GXLARGE_1HRS_FR.json, docker-compose.yml
=> Upgrade version of BoaviztAPI to 1.3.7 and adjust tests accordingly.

CHANGELOG.md, cloud-scanner-cli/src/metric_exporter.rs
Two new labels are added to all the metrics: `cloud_scanner_version` and ` boaviztapi_version`.
Per example:
```
boavizta_gwp_use_kgco2eq{awsregion="eu-west-3",country="FRA",cloud_scanner_version="4.5.6",boaviztapi_version="v1.2.3"} 0.6
```
=> feat: Return API and scanner version in the metrics output.

cloud-scanner-cli/Dockerfile
Fixes #660 
The executable is built on a Rust image, itself based on Debian. For the runtime, we should run on a Debian base as well. 
Using Alpine is causing the issue in #660
=> Fix release Docker image

docs/src/how-to/passing-aws-credentials.md, serverless.yml
While following the wiki, I could not find the permission `cloudwatch:DescribeAlarm` but `cloudwatch:DescribeAlarms` (with an `s` at the end) does exist, so I think it might have changed name.
(I did not test `serverless.yml` as I am not that familiar with deploying serveless applications and not completely sure I would not be billed by AWS for doing so)
=> AWS permission cloudwatch:DescribeAlarm does not exist (anymore ?) cloudwatch:DescribeAlarms does

CHANGELOG.md, Cargo.lock, Dockerfile, cloud-scanner-cli/Cargo.toml, cloud-scanner-cli/Dockerfile, cloud-scanner-lambda/Cargo.toml
Update to Rust v1.86 - edition 2024
=> chore: update to Rust v1.86 - edition 2024

CHANGELOG.md, cloud-scanner-cli/src/boavizta_api_v1.rs, docker-compose.yml
This could repair the unit tests and resolve https://github.com/Boavizta/cloud-scanner/issues/728, but I am not sure if there are any additional things to check to ensure everything works correctly.
=> Migrate to Boaviztapi 1.3.11
