Boavizta/cloud-scanner

- .gitignore
- Cargo.lock
- README.md
- cloud-scanner-cli/Cargo.toml
- cloud-scanner-cli/src/aws_api.rs
- cloud-scanner-cli/src/lib.rs
- cloud-scanner-cli/src/main.rs
Bumping version to v0.0.2.
Closes #14
> Update CLI options

- .dockerignore
- .github/workflows/docker-build-and-publish.yml
- CHANGELOG.md
- Cargo.lock
- Dockerfile
- README.md
- cloud-scanner-cli/Cargo.toml
- closes #27
- introduce version 0.0.3
- add changelog
- fix github action workflow
> feat: reduce docker image size

- Cargo.lock
- cloud-scanner-cli/Cargo.toml
> feat: use boaviztapi sdk 1.0.2

- CHANGELOG.md
- Cargo.toml
- README.md
- docs/src/intro.md
- docs/src/reference/limits.md
- docs/src/tutorials/quickstart-docker.md
- docs/src/tutorials/quickstart-rust-cli.md
- docs/src/tutorials/quickstart-serverless.md
Update doc accordingly.
Closes #123
> feat: cargo run executes the CLI by default.

- CHANGELOG.md
- Dockerfile
- README.md
- cloud-scanner-cli/src/lib.rs
- cloud-scanner-cli/src/metric_server.rs
- docs/src/tutorials/quickstart-docker.md
> fix: container does not expose port 8000.

- .gitignore
- dashboard-config/prometheus/prometheus.yml
- dashboard-config/provisioning/dashboards/default.yml
- dashboard-config/provisioning/dashboards/grafana-dashboard.template.json
- dashboard-config/provisioning/datasources/prometheus-datasource.yml
- docker-compose.yml
> Add Docker compose with configuration files for prometheus and grafana

- Cargo.lock
- cloud-scanner-cli/Cargo.toml
- cloud-scanner-lambda/Cargo.toml
- docker-compose.yml
> fix: in version of Boavizta images in docker compose.

- CHANGELOG.md
- Cargo.lock
- cloud-scanner-cli/Cargo.toml
- cloud-scanner-cli/src/aws_inventory.rs
- cloud-scanner-cli/src/boavizta_api_v1.rs
- cloud-scanner-cli/src/cloud_resource.rs
- cloud-scanner-cli/src/main.rs
- cloud-scanner-cli/src/metric_exporter.rs
- cloud-scanner-cli/src/metric_server.rs
- docs/src/SUMMARY.md
- docs/src/how-to/filter-by-tags.md
- docs/src/how-to/filtering-with-tags.md
Add ability to filter out instances using tags.
Closes #190 and closes #11
> Filter by tag

- README.md
- docs/src/reference/limits.md
> doc: explicit scanner limits

- CHANGELOG.md
- Cargo.lock
- README.md
- cloud-scanner-cli/Cargo.toml
- cloud-scanner-cli/src/usage_location.rs
- docs/src/reference/limits.md
> feat: support US aws regions.

- README.md
- docs/src/intro.md
- docs/src/reference/limits.md
- explict that we estimate only EC2 instances
> doc: clarify Readme

- docs/book.toml
- docs/src/tutorials/quickstart-dashboard-docker.md
> Docs: add link to the repository + fix typo

- .github/dependabot.yml
> ci: open dependabot PR's against dev branch

- Cargo.lock
- cloud-scanner-cli/Cargo.toml
- cloud-scanner-cli/src/boavizta_api_v1.rs
- cloud-scanner-cli/test-data/DEFAULT_RAW_IMPACTS_OF_M6GXLARGE_1HRS_FR.json
Reflect latest updates on API routes (using a re-generated SDK).
> Use sdk 0.3.0 alpha2

- CHANGELOG.md
- Cargo.lock
- cloud-scanner-cli/Cargo.toml
- cloud-scanner-cli/src/aws_inventory.rs
- cloud-scanner-lambda/Cargo.toml
> chore: update to latest aws sdk

- cloud-scanner-cli/src/aws_inventory.rs
- cloud-scanner-cli/src/lib.rs
- cloud-scanner-cli/src/metric_server.rs
Added a rocket server that listens on `/inventory` and provides an aws inventory as json using already existing code.
⚠️ Warning : couldn't test it as I don't have credentials for an aws instance
> Added inventory server when using cloud-scanner-api

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cloud-scanner-cli/Cargo.toml
- cloud-scanner-cli/src/cloud_resource.rs
- cloud-scanner-cli/src/impact_provider.rs
- cloud-scanner-cli/src/lib.rs
- cloud-scanner-cli/src/metric_server.rs
- cloud-scanner-cli/src/model.rs
- cloud-scanner-cli/src/usage_location.rs
- docker-compose.yml
- docs/src/SUMMARY.md
- docs/src/reference/openapi-server-mode.md
- docs/src/reference/openapi.json
- docs/src/reference/output-data.md
Closes #286 #284 #285 
Related to #310
> 310 refactor returned results into a model

- docs/src/how-to/deploy-sls.md
Rewrote the serverless deployment documentation as I thought it lacked a few important steps
> Improve serverless deployment documentation

- CHANGELOG.md
- docker-compose.yml
Update release note and version in docker compoe
> 333 add optional verbose output with the details of the calculation

- CHANGELOG.md
- Cargo.lock
- cloud-scanner-cli/Cargo.toml
- cloud-scanner-cli/src/aws_inventory.rs
- cloud-scanner-cli/src/boavizta_api_v1.rs
- cloud-scanner-cli/src/cloud_resource.rs
- cloud-scanner-cli/src/main.rs
- cloud-scanner-lambda/Cargo.toml
- docker-compose.yml
> feat: return ids of the instances attached to a volume with storage inventory

- CHANGELOG.md
- docker-compose.yml
- docs/src/explanations/methodology.md
- docs/src/reference/limits.md
> feat: use API v1.1.0 in docker-compose

- CHANGELOG.md
- Cargo.lock
- cloud-scanner-cli/Cargo.toml
- cloud-scanner-cli/src/boavizta_api_v1.rs
- cloud-scanner-cli/src/impact_provider.rs
- cloud-scanner-cli/src/lib.rs
- cloud-scanner-cli/src/metric_exporter.rs
- cloud-scanner-lambda/Cargo.toml
- dashboard-config/prometheus/prometheus.yml
- dashboard-config/provisioning/dashboards/grafana-dashboard.template.json
- docker-compose.yml
- docs/src/reference/output-data.md
Updating major version to v2.0.0 because renaming metrics introduces a breaking change.
> 379 expose individual metrics label metrics with resource ids and other metadata

- CHANGELOG.md
- cloud-scanner-cli/src/cloud_resource.rs
- cloud-scanner-cli/src/metric_exporter.rs
> feat: export resource tags in a metrics label.

- CHANGELOG.md
- Cargo.lock
- cloud-scanner-cli/Cargo.toml
- cloud-scanner-lambda/Cargo.toml
- dashboard-config/provisioning/dashboards/grafana-dashboard-cloud-impacts.template.json
- dashboard-config/provisioning/dashboards/grafana-dashboard.template.json
- dashboard-config/provisioning/datasources/prometheus-datasource.yml
- docker-compose.yml
> Release 2.0.2

- dashboard-config/provisioning/dashboards/grafana-dashboard-cloud-impacts.template.json
Slightly revamp the v2.x demo dashboard.
> feat: upate demo dashboard

- CHANGELOG.md
- docs/src/how-to/passing-aws-credentials.md
> doc: improve doc about passing aws credentials

- cloud-scanner-cli/test-data/DEFAULT_RAW_IMPACTS_OF_M6GXLARGE_1HRS_FR.json
> test: adapt tests values to BoaviztAPI v1.2.4

- docker-compose.yml
> Update image version for Boavizta API in docker-compose

- docker-compose.yml
> Update image version for Boavizta API to 1.2.4 in docker-compose

- docker-compose.yml
for Grafana and Prometheus, fixes #479
> Explicit versions of images in docker compose

- ADOPTERS.md
- CONTRIBUTING.md
Handle [issue419](https://github.com/Boavizta/cloud-scanner/issues/419).
- Added adopters file with sample
- Added contributing guidelines file
> Added adopters and contributing guidelines

- cloud-scanner-cli/test-data/DEFAULT_RAW_IMPACTS_OF_HDD.json
- cloud-scanner-cli/test-data/DEFAULT_RAW_IMPACTS_OF_SSD_1000GB_1HR.json
> chore(test): adapt integration tests values to Boaviztapi v1.3

- CHANGELOG.md
- docker-compose.yml
> Upgrade Boaviztapi and Grafana in docker compose

- CHANGELOG.md
- dashboard-config/provisioning/dashboards/grafana-dashboard-cloud-impacts.template-for-manual-import.json
- dashboard-config/provisioning/dashboards/grafana-dashboard-cloud-impacts.template.json
- docker-compose.yml
> 465 display cpu and storage size metrics in the demo dashboard

- CHANGELOG.md
- docker-compose.yml
> docker-compose: use 'default' profile by default

- CHANGELOG.md
- dashboard-config/provisioning/dashboards/grafana-dashboard-cloud-impacts.template.json
- docker-compose.yml
Adds an Overview section, emojis to each row and activate CPU usage as it wasn't on.
This also allows anonymous access to the dashboard in docker-compose, saving the users the trouble of entering admin/admin and skipping the change of password. In anonymous mode, the dashboard is also not editable, which makes it slightly easier to read. Finally, the dashboard is loaded directly, making it easier for users.
> Minor dashboard improvements and facilitate access to it

- cloud-scanner-cli/Cargo.toml
in order to publish to crates.io
see #629
> added description, repo, keywords and license 

- CHANGELOG.md
- dashboard-config/provisioning/dashboards/grafana-dashboard-cloud-impacts.template.json
> Show API and CloudScanner versions in dasboard, fixes #648

- CHANGELOG.md
- cloud-scanner-cli/Dockerfile
> Bugfix missing certificates for release Docker image

- CHANGELOG.md
- cloud-scanner-cli/src/boavizta_api_v1.rs
- docker-compose.yml
> Upgrade version of Boaviztapi to 1.3.8

- CHANGELOG.md
- cloud-scanner-cli/src/boavizta_api_v1.rs
- docker-compose.yml
- docs/src/explanations/methodology.md
> Upgrade version of Boaviztapi to 1.3.10
